#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
File: pim_ir1_to_inline_asm_translator.py
Description: Translate PIM IR-1 to C with RISC-V inline assembly.
    Refactored from generator_asm.py to operate on parsed PIM IR-1
    instead of the BLIF DAG.
Author: Mohammadhosein Gholamrezaei <uab9qt@virginia.edu> - BLIF-to-C parser generator code framework
Author: Deyuan Guo <guodeyuan@gmail.com> - Designed and implemented RISC-V inline assembly format
                                         - Support bus inputs and outputs
                                         - Support inline assembly for analog PIM
                                         - Refactored to IR-1 based translation
Date: 2024-09-17
"""

import os
import sys

_script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_script_dir, '..', '..', 'utils'))

from pim_ir1_reader import PimIr1Data


ANALOG_TO_GATE_FUNC = {
    'copy_a': 'copy',
    'copy_inout_a': 'copy_inout',
    'inv1a': 'inv1',
    'and2a': 'and2',
    'or2a': 'or2',
    'maj3a_o1': 'maj3',
    'maj3a_o2': 'maj3',
    'maj3a_o3': 'maj3',
    'zero_a': 'zero',
    'one_a': 'one',
}


def _parse_opcode(opcode):
    """Split opcode into (base, inv_suffix).

    'and2__n10' -> ('and2', '__n10')
    'inv1a__n1' -> ('inv1a', '__n1')
    'inv1'      -> ('inv1', '')
    """
    idx = opcode.find('__n')
    if idx >= 0:
        return opcode[:idx], opcode[idx:]
    return opcode, ''


def _get_gate_func(opcode_base, mode):
    """Map an IR-1 opcode base to the original gate_func name.

    Digital opcodes are identity (e.g. 'inv1' -> 'inv1').
    Analog opcodes strip the analog suffix (e.g. 'inv1a' -> 'inv1').
    """
    if mode == 'analog':
        if opcode_base not in ANALOG_TO_GATE_FUNC:
            raise ValueError(f"Unknown analog opcode: {opcode_base}")
        return ANALOG_TO_GATE_FUNC[opcode_base]
    return opcode_base


class PimIr1ToInlineAsmTranslator():
    """Translate a PimIr1Data object to C source with RISC-V inline assembly."""

    def __init__(self, ir1_data):
        """ Init """
        self.ir1 = ir1_data
        self.data_type = "int"
        self.func_name = "func"

    def generate_code(self):
        """ Generate C code """
        code = self.generate_header_files()
        code += self.generate_function_signature()
        code += self.generate_function_body()
        return code

    def generate_header_files(self):
        """ Generate header files """
        code = "// Auto Generated by Bit-Serial Compiler: C converted from BLIF\n\n"
        return code

    def generate_function_signature(self):
        """ Generate function signature """
        code = "void "
        code += self.func_name
        code += "(\n"
        code += self.generate_function_args()
        code += ")\n"
        return code

    def generate_function_args(self):
        """ Generate function args passed by pointers """
        inputs = self.ir1.inputs
        in_items = [f"{self.data_type} *{item}_pi" for item in inputs]
        outputs = self.ir1.outputs
        out_items = [f"{self.data_type} *{item}_po" for item in outputs]
        sep = ',\n\t'
        return f"\t{sep.join(in_items + out_items)}\n"

    def generate_function_body(self):
        """ Generate function body """
        code = "{\n"
        code += self.generate_temporary_variables()
        code += self.generate_temporary_variables_in()
        code += self.generate_temporary_variables_out()
        code += "\n"
        code += self.generate_all_asm_statements()
        code += "\n"
        code += self.generate_statements_output()
        code += "}\n"
        return code

    def generate_temporary_variables(self):
        """ Generate temporary variables for wires """
        wire_list = self.ir1.temps
        if len(wire_list) == 0:
            return ""
        variables = ', '.join(wire_list)
        return f"\t{self.data_type} {variables};\n"

    def generate_temporary_variables_in(self):
        """ Generate temp variables that dereference input pointers """
        inputs = self.ir1.inputs
        return f"\t{self.data_type} {', '.join([f'{item} = *{item}_pi' for item in inputs])};\n"

    def generate_temporary_variables_out(self):
        """ Generate temp variables for storing outputs """
        outputs = self.ir1.outputs
        return f"\t{self.data_type} {', '.join(outputs)};\n"

    def raise_exception(self, message):
        """ Helper function to raise an exception with a message """
        raise ValueError(message)

    def generate_clobber_list(self):
        """ Generate the RISC-V register clobbering list """
        # risc-v register: ra, a0-a7, s0-s11, t0-t6
        # ra: return address, a0-a7: argument registers, s0-s11: callee saved registers, t0-t6: temporary registers
        num_regs = self.ir1.num_regs
        regs_special = ['"ra"']
        regs_args = [f'"a{i}"' for i in range(8)]
        regs_saved = [f'"s{i}"' for i in range(12)]
        regs_temp = [f'"t{i}"' for i in range(7)]
        # clobber list: use t0-t6 for 1-7 registers, use s0-s11 for 8-19 registers
        regs_temp_to_use = 0
        regs_saved_to_use = 0
        if num_regs > 7 and num_regs <= 19:
            regs_temp_to_use = 7
            regs_saved_to_use = num_regs - 7
        if num_regs <= 7:
            regs_temp_to_use = num_regs
        regs_to_clobber = regs_special + regs_args + regs_saved[regs_saved_to_use:] + regs_temp[regs_temp_to_use:]
        return ','.join(regs_to_clobber)

    def get_asm_instructions(self, sn, opcode, outputs, inputs, clobber):
        """ Dispatch to digital or analog asm generation based on mode """
        opcode_base, inv_suffix = _parse_opcode(opcode)
        gate_func = _get_gate_func(opcode_base, self.ir1.mode)
        info = f" {gate_func}{inv_suffix}"

        if self.ir1.mode == "digital":
            return self.get_asm_instructions_digital(gate_func, info, outputs, inputs, sn, clobber)
        if self.ir1.mode == "analog":
            return self.get_asm_instructions_analog(gate_func, info, outputs, inputs, sn, clobber)
        raise ValueError(f"Error: Unknown pim mode {self.ir1.mode}")

    def get_asm_instructions_digital(self, gate_func, info, outputs, inputs, sn, clobber):
        """ Return assembly code for digital PIM """
        # =r: output register, r: input register
        # return a single line assembly code. Be careful with " and \\n
        code = ''
        if gate_func == 'inv1':
            if len(outputs) == 1 and len(inputs) == 1:
                code += f'"#PIM_OP {sn} {info} %0 %1 \\n'
                code += ' not %0, %1'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid inv1 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'and2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' and %0, %1, %2'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid and2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'nand2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' and %0, %1, %2 \\n'
                code += ' not %0, %0'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid nand2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'or2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' or %0, %1, %2'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid or2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'nor2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' or %0, %1, %2 \\n'
                code += ' not %0, %0'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid nor2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'xor2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' xor %0, %1, %2'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid xor2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'xnor2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' xor %0, %1, %2 \\n'
                code += ' not %0, %0'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid xnor2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'mux2':
            if len(outputs) == 1 and len(inputs) == 3:
                # #PIM_OP operand order: dest, sel, data1, data0 (data inputs swapped)
                code += f'"#PIM_OP {sn} {info} %0 %1 %3 %2 \\n'
                code += ' not s1, %1 \\n'
                code += ' and s2, s1, %2 \\n'
                code += ' and s3, %1, %3 \\n'
                code += ' or %0, s2, s3'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}), "r" ({inputs[2]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid mux2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'maj3':
            if len(outputs) == 1 and len(inputs) == 3:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 %3 \\n'
                code += ' and s1, %1, %2 \\n'
                code += ' and s2, %2, %3 \\n'
                code += ' and s3, %1, %3 \\n'
                code += ' or s1, s1, s2 \\n'
                code += ' or %0, s1, s3'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}), "r" ({inputs[1]}), "r" ({inputs[2]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid maj3 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'zero':
            if len(outputs) == 1 and len(inputs) == 0:
                code += f'"#PIM_OP {sn} {info} %0 \\n'
                code += ' li %0, 0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=r" ({outputs[0]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid zero operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'one':
            if len(outputs) == 1 and len(inputs) == 0:
                code += f'"#PIM_OP {sn} {info} %0 \\n'
                code += ' li %0, 0 \\n'
                code += ' not %0, %0'
                code += f'" : "=r" ({outputs[0]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid one operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        else:
            self.raise_exception(f"Error: Unknown digital gate function {gate_func}")
        return f'\tasm({code});\n'

    def get_asm_instructions_analog(self, gate_func, info, outputs, inputs, sn, clobber):
        """ Return assembly code for analog PIM """
        # return a single line assembly code. Be careful with " and \\n
        # r: input register
        # +r: both input and output
        # 0: input uses same register as output 0
        # =r: output register
        # =&r: output must be different from inputs using early clobber
        # TODO: Remove the assumption from ASM translator that the first operand of the last instruction is %0
        code = ''
        if gate_func == 'copy':
            # Note: This is regular wire copy
            if len(outputs) == 1 and len(inputs) == 1:
                code += f'"#PIM_OP {sn} {info} %0 %1 \\n'
                code += ' mv %0, %1'
                code += f'" : "=r" ({outputs[0]}) : "r" ({inputs[0]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid copy operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'copy_inout':
            # Note: copy_inout is used by wire copy inserter, supporting dependency chain while copying
            if len(outputs) == 1 and len(inputs) == 1:
                code += f'"#PIM_OP {sn} {info} %0 %1 \\n'
                code += ' mv %0, %1'
                code += f'" : "=r" ({outputs[0]}), "+r" ({inputs[0]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid copy_inout operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'inv1':
            # Note: Enforce inverter input/output to be different, to reduce the number of copies in ASM translator
            if len(outputs) == 1 and len(inputs) == 1:
                code += f'"#PIM_OP {sn} {info} %0 %1 \\n'
                code += ' not %0, %1'
                code += f'" : "=&r" ({outputs[0]}) : "r" ({inputs[0]}) : {clobber}'
            else:
                self.raise_exception(f"Invalid inv1 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'and2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' and %0, %1, %2 \\n'
                code += ' mv %1, %0 \\n'
                code += ' mv %2, %0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=&r" ({outputs[0]}), "+r" ({inputs[0]}), "+r" ({inputs[1]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid and2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'or2':
            if len(outputs) == 1 and len(inputs) == 2:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 \\n'
                code += ' or %0, %1, %2 \\n'
                code += ' mv %1, %0 \\n'
                code += ' mv %2, %0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=&r" ({outputs[0]}), "+r" ({inputs[0]}), "+r" ({inputs[1]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid or2 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'maj3':
            if len(outputs) == 1 and len(inputs) == 3:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 %3 \\n'
                code += ' and s1, %1, %2 \\n'
                code += ' and s2, %2, %3 \\n'
                code += ' and s3, %1, %3 \\n'
                code += ' or s1, s1, s2 \\n'
                code += ' or %0, s1, s3 \\n'
                code += ' mv %1, %0 \\n'
                code += ' mv %2, %0 \\n'
                code += ' mv %3, %0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=&r" ({outputs[0]}), "+r" ({inputs[0]}), "+r" ({inputs[1]}), "+r" ({inputs[2]}) : : {clobber}'
            elif len(outputs) == 2 and len(inputs) == 3:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 %3 %4 \\n'
                code += ' and s1, %2, %3 \\n'
                code += ' and s2, %3, %4 \\n'
                code += ' and s3, %2, %4 \\n'
                code += ' or s1, s1, s2 \\n'
                code += ' or %0, s1, s3 \\n'
                code += ' mv %1, %0 \\n'
                code += ' mv %2, %0 \\n'
                code += ' mv %3, %0 \\n'
                code += ' mv %4, %0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=&r" ({outputs[0]}), "=&r" ({outputs[1]}), "+r" ({inputs[0]}), "+r" ({inputs[1]}), "+r" ({inputs[2]}) : : {clobber}'
            elif len(outputs) == 3 and len(inputs) == 3:
                code += f'"#PIM_OP {sn} {info} %0 %1 %2 %3 %4 %5 \\n'
                code += ' and s1, %3, %4 \\n'
                code += ' and s2, %4, %5 \\n'
                code += ' and s3, %3, %5 \\n'
                code += ' or s1, s1, s2 \\n'
                code += ' or %0, s1, s3 \\n'
                code += ' mv %1, %0 \\n'
                code += ' mv %2, %0 \\n'
                code += ' mv %3, %0 \\n'
                code += ' mv %4, %0 \\n'
                code += ' mv %5, %0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=&r" ({outputs[0]}), "=&r" ({outputs[1]}), "=&r" ({outputs[2]}), "+r" ({inputs[0]}), "+r" ({inputs[1]}), "+r" ({inputs[2]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid maj3 operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'zero':
            if len(outputs) == 1 and len(inputs) == 0:
                code += f'"#PIM_OP {sn} {info} %0 \\n'
                code += ' li %0, 0 \\n'
                code += ' mv %0, %0'
                code += f'" : "=r" ({outputs[0]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid zero operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        elif gate_func == 'one':
            if len(outputs) == 1 and len(inputs) == 0:
                code += f'"#PIM_OP {sn} {info} %0 \\n'
                code += ' li %0, 0 \\n'
                code += ' not %0, %0'
                code += f'" : "=r" ({outputs[0]}) : : {clobber}'
            else:
                self.raise_exception(f"Invalid one operands: {len(outputs)} outputs and {len(inputs)} inputs.")
        else:
            self.raise_exception(f"Error: Unknown analog gate function {gate_func}")
        return f'\tasm({code});\n'

    def generate_all_asm_statements(self):
        """ Generate C asm statement sequence """
        # Generate the clobber list and assembly instruction mappings
        clobber = self.generate_clobber_list()

        # RISC-V inline assembly
        code = '\tasm("#PIM_OP BEGIN ##########");\n'

        # Generate assembly statements for each instruction in IR-1
        for sn, (opcode, outputs, inputs) in enumerate(self.ir1.instructions):
            code += self.get_asm_instructions(sn, opcode, outputs, inputs, clobber)

        code += '\tasm("#PIM_OP END ##########");\n'
        return code

    def generate_statements_output(self):
        """ Generate statements to store output temp vars to pointers """
        code = ""
        for port in self.ir1.outputs:
            code += "\t*" + port + '_po = ' + port + ";\n"
        return code


def translate_ir1_to_c(ir1_data):
    """Convenience function: translate PimIr1Data to C source string."""
    return PimIr1ToInlineAsmTranslator(ir1_data).generate_code()
